In [10]:
import pandas as pd

product_groups = { 
    'Cleaning Products': ['Soap', 'Shower Gel', 'Dishwasher Detergent', 'Glass Cleaner', 'Floor Cleaner'],
    'Personal Care': ['Shampoo', 'Toothpaste', 'Deodorant', 'Razor', 'Body Lotion'],
    'Food Items': ['Rice', 'Pasta', 'Olive Oil', 'Canned Beans', 'Salt', 'Milk', 'Eggs', 'Butter', 'Cheese', 'Yogurt'],
    'Beverages': ['Coffee', 'Tea', 'Orange Juice', 'Soda', 'Water', 'Milkshake', 'Smoothie', 'Energy Drink', 'Iced Tea', 'Lemonade'],
    'Snacks': ['Chips', 'Chocolate', 'Popcorn', 'Nuts', 'Cookies'],
    'Baby Care': ['Diapers', 'Baby Shampoo', 'Baby Lotion', 'Baby Powder', 'Baby Wipes'],
    'Home Appliances': ['Microwave', 'Blender', 'Vacuum Cleaner', 'Toaster', 'Coffee Maker'],
    'Electronics': ['Laptop', 'Smartphone', 'Tablet', 'Headphones', 'Smart TV'],
    'Office Supplies': ['Printer', 'Paper', 'Stapler', 'Pens', 'Notebooks'],
    'Sports Equipment': ['Yoga Mat', 'Dumbbells', 'Treadmill', 'Jump Rope', 'Resistance Bands'],
    'Outdoor Gear': ['Tent', 'Sleeping Bag', 'Backpack', 'Hiking Boots', 'Camping Stove'],
    'Pet Supplies': ['Dog Food', 'Cat Litter', 'Pet Shampoo', 'Pet Toys', 'Fish Tank'],
    'Kitchen Utensils': ['Knife Set', 'Cutting Board', 'Cookware Set', 'Mixing Bowls', 'Kitchen Scale'],
    'Home Decor': ['Throw Pillows', 'Wall Art', 'Vases', 'Candles', 'Rugs'],
    'Books': ['Fiction', 'Non-Fiction', 'Cookbooks', 'Self-Help', 'Children\'s Books'],
    'Clothing': ['T-Shirts', 'Jeans', 'Dresses', 'Sweaters', 'Jackets'],
    'Footwear': ['Sneakers', 'Sandals', 'Boots', 'Flats', 'Slippers'],
    'Toys': ['Action Figures', 'Dolls', 'Board Games', 'Building Blocks', 'Remote Control Cars'],
    'Gardening Supplies': ['Plant Pots', 'Gardening Tools', 'Fertilizer', 'Seeds', 'Watering Can'],
    'Fitness Accessories': ['Foam Roller', 'Exercise Ball', 'Jump Rope', 'Pull-Up Bar', 'Ankle Weights'],
    'Art Supplies': ['Canvas', 'Watercolor Paints', 'Sketchbook', 'Easel', 'Acrylic Paints'],
    'Home Improvement': ['Power Drill', 'Paint Rollers', 'Screwdriver Set', 'Measuring Tape', 'Toolbox'],
    'Car Accessories': ['Car Charger', 'Car Mats', 'Car Wash Kit', 'Seat Covers', 'Phone Mount'],
    'Travel Essentials': ['Luggage', 'Travel Pillow', 'Travel Adapter', 'Neck Wallet', 'Packing Cubes'],
    'Musical Instruments': ['Guitar', 'Piano', 'Violin', 'Drum Set', 'Flute'],
    'Party Supplies': ['Balloons', 'Party Hats', 'Confetti', 'Cake Toppers', 'Disposable Tableware'],
    'Tech Gadgets': ['Smartwatch', 'Bluetooth Speaker', 'Wireless Earbuds', 'Power Bank', 'Robot Vacuum'],
    'Beauty Products': ['Lipstick', 'Foundation', 'Mascara', 'Eyeshadow Palette', 'Makeup Brushes'],
    'DIY Tools': ['Circular Saw', 'Level Tool', 'Safety Glasses', 'Work Gloves', 'Extension Cord'],
    'Home Security': ['Security Camera', 'Doorbell Camera', 'Motion Sensor Lights', 'Smart Lock', 'Alarm System'],
    'Camping Gear': ['Portable Stove', 'Flashlight', 'Camp Chairs', 'Cooler', 'Lantern'],
    'Smart Home Devices': ['Smart Thermostat', 'Smart Bulbs', 'Smart Speaker', 'Smart Doorbell', 'Robot Vacuum'],
    'School Supplies': ['Backpack', 'Notebooks', 'Pens', 'Pencil Case', 'Calculator'],
    'Fitness Equipment': ['Treadmill', 'Rowing Machine', 'Elliptical Trainer', 'Kettlebell', 'Weight Bench'],
    'Travel Accessories': ['Neck Pillow', 'Luggage Tags', 'Travel Bottles', 'Passport Holder', 'Compression Socks'],
    'Winter Gear': ['Winter Coat', 'Snow Boots', 'Beanie', 'Gloves', 'Scarf'],
    'Summer Essentials': ['Sunscreen', 'Sunglasses', 'Beach Towel', 'Swimsuit', 'Flip Flops'],
    'Craft Supplies': ['Glue Gun', 'Craft Paper', 'Fabric Paint', 'Embroidery Kit', 'Glitter'],
    'Furniture': ['Sofa', 'Coffee Table', 'Dining Set', 'Bed Frame', 'Bookshelf'],
    'Home Office Supplies': ['Desk', 'Office Chair', 'Desk Lamp', 'Monitor Stand', 'Desk Organizer'],
    'Health & Wellness': ['Fitness Tracker', 'Water Bottle', 'Yoga Mat', 'Foam Roller', 'Resistance Bands'],
    'Cooking Utensils': ['Cutting Board', 'Measuring Cups', 'Mixing Bowls', 'Colander', 'Grater'],
    'Art & Crafts': ['Watercolor Paints', 'Paint Brushes', 'Clay Sculpting Kit', 'Color Pencils', 'Art Markers'],
    'Home Entertainment': ['TV', 'Soundbar', 'Streaming Device', 'Gaming Console', 'Media Player'],
    'Pet Care': ['Dog Food', 'Cat Litter', 'Pet Toys', 'Pet Shampoo', 'Bird Cage'],
    'Board Games': ['Monopoly', 'Scrabble', 'Chess', 'Risk', 'Catan'],
    'Gifts & Novelties': ['Greeting Cards', 'Candles', 'Picture Frames', 'Gift Wrap', 'Gift Baskets']
}

user_ids = ['user1', 'user2', 'user3']
for i in range(4, 10000):
    user_ids.append(f'user{i}')
pd.set_option('display.max_columns', None)

In [12]:
# create event
import pandas as pd
import random
from datetime import datetime, timedelta
import random

# Sample data for user interactions with product groups
data = {
    'userId': [],
    'productGroups': [],
    'date': [],
    'time': []
}

# Specify the number of user interactions to generate
num_interactions = 10000

# Specify the number of days for which to generate events


# Initialize a dictionary to store the last event date for each user
last_event_date = {}

# Generate random interactions
for _ in range(num_interactions):
    user_id = f'user{random.randint(1, len(user_ids))}'  # Random user ID
    if random.random() < 0.8:
        time_seconds = random.randint(100, 500)
    else:
        time_seconds = random.randint(1, 100)

    # If the user has a last event date, use the day before that date for the new event
    if user_id in last_event_date:
        event_date = last_event_date[user_id] - timedelta(days=1)
    else:
        # Otherwise, generate a random date within the specified range
        event_date = datetime.now()

    # Update the last event date for the user
    last_event_date[user_id] = event_date

    # Randomly select product groups and products for the interaction
    # selected_groups = [group for group in product_groups.keys() if random.random() < 0.7]
    # selected_products = [random.choice(product_groups[group]) for group in selected_groups]
    selected_groups = [random.choice(list(product_groups.keys()))]
    selected_products = [random.choice(product_groups[group]) for group in selected_groups] # todo  single item
    # Append the generated interaction data to the sample data dictionary
    data['userId'].append(user_id)
    data['productGroups'].append(', '.join(selected_groups))
    data['date'].append(event_date)
    data['time'].append(time_seconds)

# Create a DataFrame from the generated data
df = pd.DataFrame(data)

# Specify the output file path
output_file_path = 'events.xlsx'

# Write the DataFrame to an Excel file
df.to_excel(output_file_path, index=False)

print(f"Updated Excel file created: {output_file_path}")
display(df)

Updated Excel file created: events.xlsx

        userId         productGroups                       date  time
0     user3840              Footwear 2024-04-14 15:28:49.314648   375
1     user2596   Fitness Accessories 2024-04-14 15:28:49.314648   442
2     user7473            Food Items 2024-04-14 15:28:49.314648    94
3     user2604  Home Office Supplies 2024-04-14 15:28:49.314648   197
4     user6700             Beverages 2024-04-14 15:28:49.314648   131
...        ...                   ...                        ...   ...
9995  user1254     Cleaning Products 2024-04-11 15:28:49.318648    93
9996  user9736                Snacks 2024-04-14 15:28:49.351649   458
9997  user5414          Art Supplies 2024-04-13 15:28:49.337648   347
9998  user5706             Furniture 2024-04-13 15:28:49.321654   399
9999  user2507       Beauty Products 2024-04-13 15:28:49.341657    84

[10000 rows x 4 columns]

In [17]:
## read from DB
import pandas as pd
from sqlalchemy import create_engine

# Create a connection to the PostgreSQL database
engine = create_engine('postgresql://postgres:password@localhost:5432/lokate_dev')
# POSTGRES_URL="postgres://postgres:password@0.0.0.0:5432/lokate_dev"
# Read and preprocess event data
query = "SELECT * FROM events"
event_df = pd.read_sql(query, engine)
display(event_df.head(3))

event_df['enter_timestamp'] = pd.to_datetime(event_df['enter_timestamp'])
event_df['possible_exit_timestamp'] = pd.to_datetime(event_df['possible_exit_timestamp'])

# Calculate time in seconds
event_df['time'] = (event_df['possible_exit_timestamp'] - event_df['enter_timestamp']).dt.total_seconds().astype(int)

# Extract date from possible_exit_timestamp
event_df['date'] = event_df['possible_exit_timestamp'].dt.date

# Rename columns
event_df = event_df.rename(columns={'campaign_id': 'productGroups', 'id': 'userId'})

# Select only required columns
event_df = event_df[['userId', 'productGroups', 'date', 'time']]

# Display the transformed DataFrame
display(event_df)

,id,status,enter_timestamp,possible_exit_timestamp,location_x,location_y,radius,customer_id,branch_id,beacon_id,campaign_id
0,409b8b9c-cfb7-4f0e-840c-6468f8e6e39e,STAY,2024-04-14 18:21:52+00:00,2024-04-14 18:22:36+00:00,583,286,5.103959,a5e01a11-ad83-45d0-b91d-eb65df6fbb15,1cf4d3cf-1ee2-4a2f-a5d7-d451778332bd,ddd5a1fb-e439-43c9-aa73-4d1b203ff4f1,67125025-dd0b-47b7-beda-5e1a6d499336
1,cf11b6e4-90c7-4c44-bb6e-84141ae36fec,EXIT,2024-04-14 14:22:45+00:00,2024-04-14 14:23:32+00:00,150,430,4.058478,a5e01a11-ad83-45d0-b91d-eb65df6fbb15,1cf4d3cf-1ee2-4a2f-a5d7-d451778332bd,9c2ee807-ca93-4449-84de-69020994acbb,67125025-dd0b-47b7-beda-5e1a6d499336
2,0f31e94f-8831-46f8-ab46-a346ddd94c14,EXIT,2024-04-14 07:33:35+00:00,2024-04-14 07:34:21+00:00,279,61,6.002094,a5e01a11-ad83-45d0-b91d-eb65df6fbb15,1cf4d3cf-1ee2-4a2f-a5d7-d451778332bd,9ed82e36-3514-4e42-8fd4-42d811ef6e7b,8616de10-a389-4ecb-8ab1-3cd44f4bb07e

,userId,productGroups,date,time
0,409b8b9c-cfb7-4f0e-840c-6468f8e6e39e,67125025-dd0b-47b7-beda-5e1a6d499336,2024-04-14,44
1,cf11b6e4-90c7-4c44-bb6e-84141ae36fec,67125025-dd0b-47b7-beda-5e1a6d499336,2024-04-14,47
2,0f31e94f-8831-46f8-ab46-a346ddd94c14,8616de10-a389-4ecb-8ab1-3cd44f4bb07e,2024-04-14,46
3,75ea5cf8-3b06-4eb3-8f6a-845b6b30e06f,67125025-dd0b-47b7-beda-5e1a6d499336,2024-04-14,14
4,4b99fde8-a7f6-4854-b7b7-f4e29a5fd4c0,67125025-dd0b-47b7-beda-5e1a6d499336,2024-04-14,14
...,...,...,...,...
605,b2b2b4c5-a5ec-4d69-8e33-8411a1078f35,67125025-dd0b-47b7-beda-5e1a6d499336,2024-04-08,25
606,0fc356b0-9ccb-4d74-897d-eb6e91322e33,67125025-dd0b-47b7-beda-5e1a6d499336,2024-04-08,41
607,252678bb-8ebc-42c7-b42a-1089d0c5bc66,8616de10-a389-4ecb-8ab1-3cd44f4bb07e,2024-04-08,30
608,45d8837f-c78e-4bc1-ad8d-97de6ffa4322,8616de10-a389-4ecb-8ab1-3cd44f4bb07e,2024-04-08,50
609,26339d47-321e-458a-9f92-c30236c62859,8616de10-a389-4ecb-8ab1-3cd44f4bb07e,2024-04-08,21

In [31]:
## process the event data
import pandas as pd


# Read and preprocess event data
event_file_path = 'events.xlsx'
event_df = pd.read_excel(event_file_path)

# Convert date columns to datetime if not already
event_df['date'] = pd.to_datetime(event_df['date'])

# Initialize dictionary to store processed event data (aggregate timespent per group per user per day)
event_data = {}
group_names = list(product_groups.keys())
# Process each event row
for _, event_row in event_df.iterrows():
    user_id = event_row['userId']
    date = event_row['date'].date()

  # Skip processing if productGroups is NaN (empty)
    if pd.isna(event_row['productGroups']):
        continue
    product_groups_event = [group.strip() for group in event_row['productGroups'].split(',')]
    time_spent = event_row['time']
    
    # Ensure there's an entry in the event_data dictionary for the current (user_id, date) combination
    user_date_key = (user_id, date)
    if user_date_key not in event_data:
        event_data[user_date_key] = {f'G{i}': 0 for i in range(len(group_names))}
    
    # Update timespent for each group in the event (accumulate timespent per group per day)
    for group in product_groups_event:
        if group in product_groups:
            # if random.random() < 0.8:
            #     time_spent = random.randint(251, 500)
            # else:
            #     time_spent = random.randint(1, 250)
            

            mapped_group_index = group_names.index(group)
            event_data[user_date_key][f'G{mapped_group_index}'] += time_spent

# Convert event_data dictionary to a list of dictionaries (each representing a (userId, date) entry)
event_processed_data = [{'userId': user_id, 'date': date, **data} for (user_id, date), data in event_data.items()]

# Create dataframe from event_processed_data
event_processed_df = pd.DataFrame(event_processed_data)


# Display the processed event dataframe
# print("Processed Event DataFrame:")
display(event_processed_df)

,userId,date,G0,G1,G2,G3,G4,G5,G6,G7,G8,G9,G10,G11,G12,G13,G14,G15,G16,G17,G18,G19,G20,G21,G22,G23,G24,G25,G26,G27,G28,G29,G30,G31,G32,G33,G34,G35,G36,G37,G38,G39,G40,G41,G42,G43,G44,G45,G46
0,user6244,2024-04-14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,245,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,user5464,2024-04-14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,235,0,0,0,0,0,0,0,0,0,0,0,0,0
2,user3323,2024-04-14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,345,0,0,0,0,0,0,0,0,0,0,0,0,0
3,user1162,2024-04-14,0,0,0,210,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,user7262,2024-04-14,0,320,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,user8735,2024-04-14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,112,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9996,user2082,2024-04-13,0,0,0,0,0,0,0,373,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9997,user4006,2024-04-11,0,0,0,0,0,0,0,0,0,0,0,0,85,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9998,user7303,2024-04-10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,465,0,0,0,0,0,0,0,0,0,0,0,0,0
9999,user1569,2024-04-13,0,0,0,0,0,0,0,0,0,0,0,0,151,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [32]:
#Generate purhase data using event data
import pandas as pd
from datetime import datetime, timedelta
import random

def create_purchase_list_from_events(event_df, product_groups, output_file_path):
    # Create an empty list to store purchase records
    purchases = []

    # Iterate through each row in the event DataFrame
    for _, row in event_df.iterrows():
        user_id = row['userId']
        purchase_date = row['date']

        # Determine the product groups bought by the user on the purchase date
        bought_groups = [int(group[1:]) for group, time_spent in row.items() if group.startswith('G') and time_spent > 0]

        selected_products = []
        for index in bought_groups:
            group = group_names[index]
            num_products = min(1, len(product_groups[group])) 
            time_spent = row[f'G{index}']

            # Adjust purchase probability based on time spent
            if time_spent > 100:
                purchase_prob = random.random() < 0.8
            else:
                purchase_prob = random.random() < 0.4

            if not purchase_prob:
                continue

            # Randomly select products from the current group
            products_from_group  = random.sample(product_groups[group], num_products)
            selected_products.extend(products_from_group)
       
        # Join the selected products into a comma-separated string
        product_list = ', '.join(selected_products)

        # Append purchase record to the list
        purchases.append({'Purchase Date': purchase_date, 'User ID': user_id, 'Product': product_list})

    df = pd.DataFrame(purchases)

    # Write the DataFrame to an Excel file
    df.to_excel(output_file_path, index=False)
    print(f"Purchase list created: {output_file_path}")

output_file_path = 'purchase_list_random.xlsx'
create_purchase_list_from_events(event_processed_df, product_groups, output_file_path)
display(df)

Purchase list created: purchase_list_random.xlsx

        userId      productGroups                       date  time
0     user6244           Footwear 2024-04-14 13:38:45.719534   245
1     user5464  Fitness Equipment 2024-04-14 13:38:45.719534   235
2     user3323  Fitness Equipment 2024-04-14 13:38:45.719534   345
3     user1162          Beverages 2024-04-14 13:38:45.719534   210
4     user7262      Personal Care 2024-04-14 13:38:45.719534   320
...        ...                ...                        ...   ...
9995  user8735  Travel Essentials 2024-04-14 13:38:45.792530   112
9996  user2082        Electronics 2024-04-13 13:38:45.766531   373
9997  user4006   Kitchen Utensils 2024-04-11 13:38:45.721534    85
9998  user7303  Fitness Equipment 2024-04-10 13:38:45.729529   465
9999  user1569   Kitchen Utensils 2024-04-13 13:38:45.727530   151

[10000 rows x 4 columns]

In [33]:
## merge purchase data with event data
def map_product_to_group(product):
    if not isinstance(product, str):
        return None

    if ',' in product:
        products = [p.strip() for p in product.split(',')]  # Split products by comma and remove extra spaces
    else:
        products = [product.strip()]  # Handle single product

    group_indexes = set()
    for p in products:
        for index, (group_name, group_products) in enumerate(product_groups.items()):
            if p in group_products:
                group_indexes.add(index)
                break
    return group_indexes if group_indexes else None

# Read and preprocess purchase data
purchase_file_path = 'purchase_list_random.xlsx'
purchase_df = pd.read_excel(purchase_file_path)

# Map purchased products to their corresponding product group indexes
purchase_df['Product Group Indexes'] = purchase_df['Product'].apply(map_product_to_group)

# Convert 'Purchase Date' to datetime and ensure the date format matches
purchase_df['Purchase Date'] = pd.to_datetime(purchase_df['Purchase Date']).dt.date

# Aggregate purchases with the same dates and user IDs
def combine_group_indexes(group_indexes):
    combined = set()
    for indexes in group_indexes.dropna():
        combined.update(indexes)
    return combined if combined else None

purchase_df_grouped = purchase_df.groupby(['User ID', 'Purchase Date'])['Product Group Indexes'].agg(combine_group_indexes).reset_index()

# Merge event_processed_df with aggregated purchase information based on (User ID, date)
merged_df = pd.merge(event_processed_df, purchase_df_grouped, how='left', left_on=['userId', 'date'], right_on=['User ID', 'Purchase Date'])

# Drop redundant columns after merge
merged_df.drop(['User ID', 'Purchase Date'], axis=1, inplace=True)

# Add Pi columns for each group in product_groups based on the purchase data
for i, group_name in enumerate(product_groups.keys()):
    group_index_column = f'G{i}'
    pi_column = f'P{i}'
    def check_conditions(row, i, group_index_column):
        if isinstance(row['Product Group Indexes'], set):
            if i in row['Product Group Indexes'] and row[group_index_column] > 0:
                return 1
        return 0

    merged_df[pi_column] = merged_df.apply(lambda row: check_conditions(row, i, group_index_column), axis=1)

# merged_df.drop(['Product Group Indexes', 'Product'], axis=1, inplace=True)
# Display the merged dataframe
print("Merged DataFrame:")
display(merged_df.head())

Merged DataFrame:

,userId,date,G0,G1,G2,G3,G4,G5,G6,G7,G8,G9,G10,G11,G12,G13,G14,G15,G16,G17,G18,G19,G20,G21,G22,G23,G24,G25,G26,G27,G28,G29,G30,G31,G32,G33,G34,G35,G36,G37,G38,G39,G40,G41,G42,G43,G44,G45,G46,Product Group Indexes,P0,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28,P29,P30,P31,P32,P33,P34,P35,P36,P37,P38,P39,P40,P41,P42,P43,P44,P45,P46
0,user6244,2024-04-14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,245,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,None,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,user5464,2024-04-14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,235,0,0,0,0,0,0,0,0,0,0,0,0,0,{33},0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
2,user3323,2024-04-14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,345,0,0,0,0,0,0,0,0,0,0,0,0,0,{33},0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3,user1162,2024-04-14,0,0,0,210,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,{3},0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,user7262,2024-04-14,0,320,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,None,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [34]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.multioutput import MultiOutputClassifier
import pickle

# Assuming 'merged_df' and 'product_groups' are defined appropriately

# Drop unnecessary columns
model_df = merged_df.drop(['userId', 'date', 'Product Group Indexes'], axis=1)

# Define features (X) and target (y)
X = model_df.drop([f'P{i}' for i in range(len(product_groups))], axis=1)  # Drop purchase indicator columns
y = model_df[[f'P{i}' for i in range(len(product_groups))]]  # Keep purchase indicator columns as target

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize a multi-output classifier with RandomForestClassifier
classifier = MultiOutputClassifier(RandomForestClassifier(random_state=42))

# Train the classifier
classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = classifier.predict(X_test)

# Evaluate the classifier
print("Classification Report:")
print(classification_report(y_test, y_pred, zero_division=1))  # zero_division parameter handles undefined metrics

# Save the trained model as a pickle string
saved_model = pickle.dumps(classifier)

# Save the model to disk
with open('model.pkl', 'wb') as file:
    pickle.dump(classifier, file)

Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.72      0.74        32
           1       0.78      0.81      0.79        31
           2       0.77      0.79      0.78        29
           3       0.84      0.75      0.79        28
           4       0.73      0.75      0.74        40
           5       0.78      0.72      0.75        40
           6       0.74      0.65      0.69        26
           7       0.79      0.63      0.70        35
           8       0.62      0.75      0.68        24
           9       0.81      0.86      0.83        35
          10       0.70      0.75      0.72        28
          11       0.58      0.67      0.62        27
          12       0.81      0.78      0.79        37
          13       0.63      0.55      0.59        31
          14       0.81      0.59      0.68        29
          15       0.68      0.73      0.70        26
          16       0.80      0.76      0.78        37
          17       0.76      0.82      0.79        34
          18       0.91      0.74      0.82        39
          19       0.54      0.48      0.51        27
          20       0.64      0.64      0.64        25
          21       0.72      0.93      0.81        28
          22       0.83      0.91      0.87        32
          23       0.69      0.72      0.71        25
          24       0.83      0.77      0.80        39
          25       0.79      0.85      0.82        40
          26       0.72      0.81      0.76        26
          27       0.70      0.57      0.63        28
          28       0.67      0.90      0.77        20
          29       0.73      0.77      0.75        31
          30       0.77      0.79      0.78        29
          31       0.56      0.45      0.50        22
          32       0.35      0.46      0.40        13
          33       0.88      0.70      0.78        30
          34       0.86      0.75      0.80        32
          35       0.77      0.72      0.74        32
          36       0.72      0.78      0.75        27
          37       0.70      0.84      0.76        31
          38       0.76      0.76      0.76        29
          39       0.70      0.76      0.73        25
          40       0.20      0.25      0.22        12
          41       0.39      0.47      0.43        19
          42       0.67      0.44      0.53        27
          43       0.84      0.87      0.86        31
          44       0.00      0.00      1.00         5
          45       1.00      0.88      0.93        32
          46       0.83      0.65      0.73        23

   micro avg       0.73      0.73      0.73      1348
   macro avg       0.71      0.70      0.72      1348
weighted avg       0.74      0.73      0.73      1348
 samples avg       0.82      0.81      0.64      1348

In [35]:
from sklearn.metrics import confusion_matrix

# Predict on the test set
y_pred = classifier.predict(X_test)

# Print confusion matrix for each output
for i in range(y_test.shape[1]):
    print(f"Output {i+1}:")
    print(confusion_matrix(y_test.iloc[:, i], [pred[i] for pred in y_pred]))
    print()

Output 1:
[[1961    7]
 [   9   23]]

Output 2:
[[1962    7]
 [   6   25]]

Output 3:
[[1964    7]
 [   6   23]]

Output 4:
[[1968    4]
 [   7   21]]

Output 5:
[[1949   11]
 [  10   30]]

Output 6:
[[1952    8]
 [  11   29]]

Output 7:
[[1968    6]
 [   9   17]]

Output 8:
[[1959    6]
 [  13   22]]

Output 9:
[[1965   11]
 [   6   18]]

Output 10:
[[1958    7]
 [   5   30]]

Output 11:
[[1963    9]
 [   7   21]]

Output 12:
[[1960   13]
 [   9   18]]

Output 13:
[[1956    7]
 [   8   29]]

Output 14:
[[1959   10]
 [  14   17]]

Output 15:
[[1967    4]
 [  12   17]]

Output 16:
[[1965    9]
 [   7   19]]

Output 17:
[[1956    7]
 [   9   28]]

Output 18:
[[1957    9]
 [   6   28]]

Output 19:
[[1958    3]
 [  10   29]]

Output 20:
[[1962   11]
 [  14   13]]

Output 21:
[[1966    9]
 [   9   16]]

Output 22:
[[1962   10]
 [   2   26]]

Output 23:
[[1962    6]
 [   3   29]]

Output 24:
[[1967    8]
 [   7   18]]

Output 25:
[[1955    6]
 [   9   30]]

Output 26:
[[1951    9]
 [   6   34]]

Output 27:
[[1966    8]
 [   5   21]]

Output 28:
[[1965    7]
 [  12   16]]

Output 29:
[[1971    9]
 [   2   18]]

Output 30:
[[1960    9]
 [   7   24]]

Output 31:
[[1964    7]
 [   6   23]]

Output 32:
[[1970    8]
 [  12   10]]

Output 33:
[[1976   11]
 [   7    6]]

Output 34:
[[1967    3]
 [   9   21]]

Output 35:
[[1964    4]
 [   8   24]]

Output 36:
[[1961    7]
 [   9   23]]

Output 37:
[[1965    8]
 [   6   21]]

Output 38:
[[1958   11]
 [   5   26]]

Output 39:
[[1964    7]
 [   7   22]]

Output 40:
[[1967    8]
 [   6   19]]

Output 41:
[[1976   12]
 [   9    3]]

Output 42:
[[1967   14]
 [  10    9]]

Output 43:
[[1967    6]
 [  15   12]]

Output 44:
[[1964    5]
 [   4   27]]

Output 45:
[[1992    3]
 [   5    0]]

Output 46:
[[1968    0]
 [   4   28]]

Output 47:
[[1974    3]
 [   8   15]]

In [46]:
import pickle

# Load the model from disk
with open('model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

data = {f'G{i}': [0] for i in range(47)}

# Create a DataFrame from the dictionary
sample = pd.DataFrame(data)

# Update 'G8' to 190
sample['G1'] = 250

# Load the model from disk
with open('model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

# Use the loaded model to make predictions
probabilities = loaded_model.predict_proba(sample)


for i, prob in enumerate(probabilities):
    print(f"Probability for class {i}: {prob[0][1]}")

Probability for class 0: 0.0
Probability for class 1: 0.9
Probability for class 2: 0.0
Probability for class 3: 0.0
Probability for class 4: 0.0
Probability for class 5: 0.0
Probability for class 6: 0.0
Probability for class 7: 0.0
Probability for class 8: 0.0
Probability for class 9: 0.0
Probability for class 10: 0.0
Probability for class 11: 0.0
Probability for class 12: 0.0
Probability for class 13: 0.0
Probability for class 14: 0.0
Probability for class 15: 0.0
Probability for class 16: 0.0
Probability for class 17: 0.0
Probability for class 18: 0.0
Probability for class 19: 0.0
Probability for class 20: 0.0
Probability for class 21: 0.0
Probability for class 22: 0.0
Probability for class 23: 0.0
Probability for class 24: 0.0
Probability for class 25: 0.0
Probability for class 26: 0.0
Probability for class 27: 0.0
Probability for class 28: 0.0
Probability for class 29: 0.0
Probability for class 30: 0.0
Probability for class 31: 0.0
Probability for class 32: 0.0
Probability for class 33: 0.0
Probability for class 34: 0.0
Probability for class 35: 0.0
Probability for class 36: 0.0
Probability for class 37: 0.0
Probability for class 38: 0.0
Probability for class 39: 0.0
Probability for class 40: 0.0
Probability for class 41: 0.0
Probability for class 42: 0.0
Probability for class 43: 0.0
Probability for class 44: 0.0
Probability for class 45: 0.0
Probability for class 46: 0.0